#!/bin/bash

# $1: Mensaje a loguear ; $2: Tipo del mensaje
function log {
    $DIRBIN/LOGEP DEMONEP "$1" "$2"
}

seguir=true
trap ctrl_c INT

function ctrl_c {
	echo "Finalizando..."
	seguir=false
}

function loop {
	contador=1
	proc_pid=0
	while ( $seguir )
	do
		log "Demonep ciclo nro. $contador" "INFO"
		contador=$(( contador + 1 ))
		IFS='
		'
		for archivo in $(ls $DIRREC)
		do
			valido="true"
			log "Archivo detectado: $archivo" "INFO"

			# Validar que el archivo sea texto
			if file "$DIRREC/$archivo" | grep -vq text$; then
				# Es Binario
				log "Archivo rechazado, motivo no es un archivo de texto." "INFO"
				valido="false"
			fi

			# Validar que el archivo no este vacio
			if [ ! -s "$DIRREC/$archivo" ]; then
				log "Archivo rechazado, motivo: archivo vacio." "INFO"
				valido="false"
			fi

			# Validar formato del archivo
			# ejecutado_<año_presupuestario>_<cod_provincia>_<aniomesdia>.csv
			# ejecutado_2016_1_20151222
			formato_valido="true"
			ejec=$(echo "$archivo" | cut -d_ -f1)
			anio=$(echo "$archivo" | cut -d_ -f2)
			codigo=$(echo "$archivo" | cut -d_ -f3)
			fecha=$(echo "$archivo" | cut -d_ -f4 | cut -d. -f1)

			if [ $ejec != "ejecutado" ]; then
				formato_valido="false"
				log "Archivo rechazado, motivo: formato de nombre incorrecto." "INFO"
			fi

			if [ $anio != $(date +%Y) ]; then
				formato_valido="false"
				log "Archivo rechazado, motivo: año $anio incorrecto." "INFO"
			fi
			cat "$DIRMAE/provincias.csv" | grep -q $codigo
			if [ $? -eq 1 ]; then
				formato_valido="false"
				log "Archivo rechazado, motivo: provincia $codigo incorrecta." "INFO"
			fi

			if [ $fecha ]; then
				# Regex compleja. Lo que hago es convertir el formato de aaaammdd a mm/dd/aaaa para poder validar con date
				formato_pedido=$(echo $fecha | sed 's/\([0-9]\{4\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)/\2\/\3\/\1/')
				date "+%m/%d/%Y" -d $formato_pedido > /dev/null  2>&1
 				if [ $? -ne 0 ]; then
 					formato_valido="false"
 				fi
 				anio=$(date "+%Y")
 				desde=$(grep "\s*$anio.*Anual" $DIRMAE/trimestres.csv | cut -d';' -f3)
 				hasta=$(grep "\s*$anio.*Anual" $DIRMAE/trimestres.csv | cut -d';' -f4)
 				fecha=$fecha
				desde=$(echo $desde | sed 's/\([0-9]\{2\}\)\/\([0-9]\{2\}\)\/\([0-9]\{4\}\)/\3\2\1/')
                d=`echo "$desde" | cut -d "/" -f 1`
                m=`echo "$desde" | cut -d "/" -f 2`
                y=`echo "$desde" | cut -d "/" -f 3`
                desde="$y$m$d"

				hasta=$(echo $hasta | sed 's/\([0-9]\{2\}\)\/\([0-9]\{2\}\)\/\([0-9]\{4\}\)/\3\2\1/')
				d=`echo "$hasta" | cut -d "/" -f 1`
                m=`echo "$hasta" | cut -d "/" -f 2`
                y=`echo "$hasta" | cut -d "/" -f 3`
                hasta="$y$m$d"
 				if [ "$fecha" \< "$desde" ] || [ "$fecha" == "$hasta" ] || [ "$fecha" \> "$hasta" ]; then
 					formato_valido="false"
 				fi
 				hoy=$(date "+%YYYY%mm%dd")

 				if [ "$fecha" \> "$hoy" ]; then
 					formato_valido="false"
 				fi

 				if [ $formato_valido == "false" ]; then
 					log "Archivo rechazado, motivo: fecha $fecha incorrecta." "INFO"
 				fi
			fi

			if [ $valido == "true" ] && [ $formato_valido == "true" ]; then
				log "Archivo aceptado" "INFO"
				./MOVEP $DIRREC/$archivo $DIROK DEMONEP
			else
				log "Archivo rechazado" "INFO"
				./MOVEP $DIRREC/$archivo $DIRNOK DEMONEP
			fi

		done
		cantidad=$(ls "$DIROK" | wc -l)
		if [ $cantidad -gt 0 ]; then
			ps ax | grep -q "^\s*$proc_pid"
			# Si falla el grep, no esta corriendo procep
			if [ $? -eq 1 ]; then
				# No esta ejecutandose procep
				$DIRBIN/PROCEP &
				proc_pid=$(echo $!)
				log "Procep corriendo bajo el no.: $proc_pid" "INFO"
			else
				# Se esta ejecutando procep
				log "Invocación de Procep pospuesta para el siguiente ciclo" "INFO"
			fi
		fi

		sleep 30
	done
}

# Cuerpo principal
if ! [ -f "$DIRCONF/INSTALEP.conf" ] ; then
    echo "EPLAM no está adecuadamente inicializado en el sistema. Ejecute INSTALEP."
    exit $ERROR
fi

# Busco el proceso para ver si se esta ejecutando
last_pid=$(cat $DIRCONF/INSTALEP.conf | grep "DEMONEP_PID" | cut -d= -f2)
ps ax | grep "^\s*$last_pid" &> /dev/null
if [ $? -eq 0 ]; then
	#Se esta ejecutando
	echo "Ya se esta ejecutando DEMONEP. Saliendo..."
	exit
else
	# Ejecutando por primera vez, actualizo INSTALEP.conf
	sed -i -e "s/DEMONEP_PID=[0-9]*/DEMONEP_PID=$$/g" $DIRCONF/INSTALEP.conf
fi

loop
