#!/bin/bash

#TODO(tomas) Comentar esta linea
GRUPO="."

dir_maestros="$GRUPO"/mae/
dir_novedades="$GRUPO"/nov/
dir_rec="$GRUPO"/rec/

# $1: Mensaje a loguear ; $2: Tipo del mensaje
function log {
    $DIRBIN/LOGEP INITEP "$1" "$2"
}

function validar_ambiente {
	# TODO(tomas) Realizar la validacion
	# Misma validacion de initep.sh
	# Copiar
	echo "true"
	#echo "false"
}

seguir=true
trap ctrl_c INT

function ctrl_c {
	echo "Finalizando..."
	seguir=false
}

function loop {
	contador=1
	while ( $seguir )
	do
		log "Demonep ciclo nro. $contador" "INFO"
		contador=$(( contador + 1 ))
		IFS='
		'
		for archivo in $(ls $dir_rec)
		do
			valido="true"
			log "Archivo detectado: $archivo" "INFO"

			# Validar que el archivo sea texto
			if file "$dir_rec$archivo" | grep -vq text$; then
				# Es Binario
				log "Archivo rechazado, motivo no es un archivo de texto." "INFO"
				valido="false"
			fi

			# Validar que el archivo no este vacio
			if [ ! -s "$dir_rec$archivo" ]; then
				log "Archivo rechazado, motivo: archivo vacio." "INFO"
				valido="false"
			fi

			# Validar formato del archivo
			# ejecutado_<año_presupuestario>_<cod_provincia>_<aniomesdia>.csv
			# ejecutado_2016_1_20151222
			formato_valido="true"
			ejec=$(echo "$archivo" | cut -d_ -f1)
			anio=$(echo "$archivo" | cut -d_ -f2)
			codigo=$(echo "$archivo" | cut -d_ -f3)
			fecha=$(echo "$archivo" | cut -d_ -f4 | cut -d. -f1)

			if [ $ejec != "ejecutado" ]; then
				formato_valido="false"
				log "Archivo rechazado, motivo: formato de nombre incorrecto." "INFO"
			fi

			if [ $anio != $(date +%Y) ]; then
				formato_valido="false"
				log "Archivo rechazado, motivo: año $anio incorrecto." "INFO"
			fi
			cat "$dir_maestrosprovincias.csv" | grep -q $codigo
			if [ $? -eq 1 ]; then
				formato_valido="false"
				log "Archivo rechazado, motivo: provincia $codigo incorrecta." "INFO"
			fi

			# TODO(tomas) Validar el cuarto campo FECHA
			#if [ $fecha ]; then
			#	echo "fecha"
			#fi

			if [ $valido == "true" && $formato_valido == "true" ]; then
				# TODO(tomas) llamar al movep DIRNOK
				log "Archivo aceptado" "INFO"
			else
				# TODO(tomas) llamar al movep DIROK
				log "Archivo rechazado" "INFO"
			fi

		done
		sleep 300
	done
}

# Cuerpo principal
valido=$(validar_ambiente)
if [ $valido == "false" ] ; then
	echo "El ambiente no fue correctamente inicializado. Saliendo..."
	exit
fi

loop


