#!/bin/bash

# Invocación: LOGEP COMMAND MESSAGE ERRLVL
# E.g.: LOGEP $0 'Error en el archivo' 'ERR'

WHERE=`echo $1 | rev | cut -d/ -f1 | rev | cut -d. -f1`
LOGFILE="$DIRLOG/$WHERE.log" # Usa el nombre del comando como nombre de archivo
if [ 'INSTALEP' = $WHERE ];
then
   LOGFILE="$DIRCONF/INSTALEP.log"
fi

if [ ! -f $LOGFILE ]; then
    touch $LOGFILE
    if [ ! -f $LOGFILE ]; then
        echo "No existe el archivo $LOGFILE y no se puede generar"
    fi
fi

if [ $# -eq 3 ]; then
    WHY=$3
else
    WHY="INFO"
fi

WHO=$USER
WHEN=`date "+%Y/%m/%d %T"`
WHAT=$2

if [ ! -f $LOGFILE ];
then
    touch $LOGFILE
fi

LOGLINE=$(echo $WHO $WHEN $WHERE $WHAT $WHY)
FILESIZE=$(wc -c $LOGFILE | cut -d' ' -f1)

if [ $FILESIZE -ge $LOGSIZE ];
then
    TMPFILE="templog.log"
    tail -n100 $LOGFILE >> $TMPFILE
    echo "Log Excedido." >> $TMPFILE
    mv $TMPFILE $LOGFILE
fi

echo "$WHO $WHEN $WHERE $WHAT $WHY" >> $LOGFILE
