#!/bin/bash

# Invocación: LOGEP COMMAND MESSAGE ERRLVL
# E.g.: LOGEP $0 'Error en el archivo' 'ERR'

# Ademas el directorio donde se encuentra la configuracion de instalacion es dirconf
WHERE=`echo $1 | rev | cut -d/ -f1 | rev | cut -d. -f1`
# Me tengo que posicionar en $GRUPO para esto
# en version pseudocodigo
while [ ! -d dirconf ] && [ ! $PWD = "/" ]; do
   cd ..
done
if [ $PWD = "/" ]; then
    echo "tu vieja gil"
else
    DIRCONF=$PWD/dirconf
fi

if [ 'INSTALEP' = "$WHERE" ];
then
   LOGFILE="$DIRCONF/INSTALEP.log"
else
   DIRLOG=`grep DIRLOG ../dirconf/INSTALEP.conf | cut -d '=' -f 2`
   LOGFILE="$DIRLOG/$WHERE.log" # Usa el nombre del comando como nombre de archivo    
fi

if [ ! -f "$LOGFILE" ]; then
    touch $LOGFILE
    if [ ! -f $LOGFILE ]; then
        echo "No existe el archivo $LOGFILE y no se puede generar"
    fi
fi

if [ $# -eq 3 ]; then
    WHY=$3
else
    WHY="INFO"
fi

WHO=$USER
WHEN=`date "+%Y/%m/%d %T"`
WHAT=$2

if [ ! -f $LOGFILE ];
then
    touch $LOGFILE
fi

LOGLINE=$(echo $WHO $WHEN $WHERE $WHAT $WHY)
FILESIZE=$(wc -c $LOGFILE | cut -d' ' -f1)
echo $FILESIZE
if [ $FILESIZE -ge 5242880 ];
then
    TMPFILE="templog.log"
    tail -n100 $LOGFILE >> $TMPFILE
    echo "Log Excedido." >> $TMPFILE
    mv $TMPFILE $LOGFILE
fi

echo -e "$WHO $WHEN $WHERE [$WHY] $WHAT" >> $LOGFILE
