#!/bin/bash
# test init
GRUPO="$(pwd -P)" # Obtengo el directorio del script
cd $GRUPO
DIRCONF="$GRUPO"/dirconf # Directorio del archivo de configuracion
DIRBIN="$GRUPO"
DIRMAE="$GRUPO"/mae
DIRREC="$GRUPO"/nov
DIROK="$GRUPO"/ok
DIRPROC="$GRUPO"/imp/proc
DIRINFO="$GRUPO"/rep
DIRLOG="$GRUPO"/log
DIRNOK="$GRUPO"/nok

VAR_INITEP="true"
#test end

# $1: Mensaje a loguear ; $2: Tipo del mensaje
function log {
  echo "$1" "$2"
  #$DIRBIN/LOGEP PROCEP "$1" "$2"
}

seguir=true
trap ctrl_c INT

function ctrl_c {
	echo "Finalizando..."
	seguir=false
}

function loop {
	log "Cantidad de archivos a procesar: $(ls -l $DIROK| wc -l)" "WAR"
	while ( $seguir )
	do
		for archivo in $(ls $DIROK)
		do
			archivo_valido="true"
			# Validar que no esté dentro de los procesados
			if [ -f "$DIRPROC/$archivo" ] ; then
		    log "Archivo Duplicado. Se rechaza el archivo $archivo"
				archivo_valido="false"	
			fi

			#A efectos de este TP, bastara con verificar el primer registro para determinar si el formato es
            #correcto.
            #Si la cantidad de campos del primer registro no se corresponde con el formato establecido, asumir
            #que el archivo está dañado, rechazar el archivo completo y grabar en el log un mensaje aclaratorio,
            #como ser:
            #Estructura inesperada. Se rechaza el archivo <nombre del archivo>.
            #El archivo rechazado se lo mueve a DIRNOK empleando la función Movep.

            linea=$(head -n 1 $DIROK/$archivo)

            IFS=';' read -ra valores <<< "$linea"
#
#            echo ${valores[0]}

            # Iteración de registros dentro de cada archivo
			# 1) Validar formato correcto del archivo (Primer registro)
			# 1a) Incorrecto: ./MOVEP $DIRREC/$archivo $DIRNOK PROCEP
			# 1b) Correcto: -> Grabar en log: Archivo a procesar <nombre del archivo>.

            if [ ${valores[0]} != "ID_EJE" ] || [ ${valores[1]} != "FECHA_EJE" ] || [ ${valores[2]} != "COD_CEN_EJE" ] ||
                [ ${valores[3]} != "NOM_ACT_EJE" ] || [ ${valores[4]} !=  "NOM_TRI_EJE" ] || [ ${valores[5]} != "GASTO_EJE" ]; then
			    log "Estructura inesperada. Se rechaza el archivo $archivo."
			    ./MOVEP $DIROK/$archivo $DIRNOK PROCEP
            else
                log "Archivo a procesar: $archivo"
                while IFS='' read -r linea || [[ -n "$linea" ]]; do
                    echo "Text read from file: $linea"
                done < "$DIROK/$archivo"
            fi


            #Validación Centro de Presupuesto: El centro de presupuesto debe existir en el maestro de centros
            #Validación de Actividad: La actividad debe existir en el maestro de actividades
            #Validación Trimestre: El trimestre debe existir en la tabla de trimestres y el trimestre debe ser del año
            #presupuestario corriente
            #Validación de Fecha: la fecha indicada en el registro debe ser una fecha valida; menor o igual a la
            #fecha del nombre del archivo y estar comprendida entre la fecha de inicio del trimestre
            #(FDESDE_TRI) y la fecha de fin del trimestre (FHASTA_TRI)
            #Validación de Gasto: el importe de gasto debe ser mayor a cero.



			# 2) Validar los campos

			# 3) Resultado de REGISTRO
			# 3a) Grabar registro aceptado en DIRPROC/ejecutado-<año presupuestario>
			# 3b) Grabar registro rechazado en DIRPROC/rechazado-<año presupuestario>

			# Fin iteración

			# 4) Totalizar
			# 4a) Registros leidos
			# 4b) Registros rechazados
			# 4a) Registros aceptados

		done
		seguir=false
	done
}

# Cuerpo principal

# Verificar si el ambiente ya fue inicializado
if [ -z "$VAR_INITEP" ] ; then
	echo "El ambiente no fue inicializado. Para iniciar ejecute INITEP nuevamente."
else
	loop
fi